Fix resize_vm() cancel and submission errors
This is to fix the following error when submiting / canceling
vm resize:

Error caught: [NoMethodError] undefined method `[]' for nil:NilClass
app/controllers/vm_cloud_controller.rb:41:in `resize_vm'

https://bugzilla.redhat.com/show_bug.cgi?id=1331052
[Original commit e0e6904a6ca59e371e1cff8aa89c688ff94ec02c]