Fix traceback in instance reconfigure screen when nil size root disk
Some instances (Amazon) do not seem to have the info about root disk
size available.

Fixing the following error:

Error caught: [NoMethodError] undefined method `bytes' for nil:NilClass
app/models/flavor.rb:36:in `name_with_details'
app/views/vm_common/_resize.html.haml:13

https://bugzilla.redhat.com/show_bug.cgi?id=1331052
[Original commit 90181a13c4cca3191c80c1141fe4886b7b80681f]