Treebuilder should expand hosts only when expansion defined
Since 94d45096, the datacenter tree is using x_get_tree_host_kids
however, the other trees may also contain Host nodes while not
defining Host kids.

Addressing error nodes on the Bottleneck page):
[NoMethodError] undefined method `x_get_tree_host_kids' for #<TreeBuilderUtilization:0x007fc758b5ffa0>
app/presenters/tree_builder.rb:376:in `x_get_tree_objects'
app/presenters/tree_builder.rb:435:in `x_build_node'
app/presenters/tree_builder.rb:448:in `x_build_node_dynatree'
app/presenters/tree_builder.rb:213:in `block in x_get_child_nodes'
app/presenters/tree_builder.rb:212:in `map'
app/presenters/tree_builder.rb:212:in `x_get_child_nodes'
app/presenters/tree_builder.rb:490:in `tree_add_child_nodes'
app/controllers/application_controller/tree_support.rb:35:in `tree_autoload_dynatree'
[Original commit 0b32b1081569f71a53d1d12535ac466cb080daa4]