Fix error when creating control policy copy
This is to address the following error:

Error caught: [NoMethodError] undefined method `%' for
app/controllers/miq_policy_controller/policies.rb:110:in `policy_copy'
[Original commit 15aa4596c655a38803a99a36cdb8e10ea3a350ee]