Fix error when rendering custom button set toolbar
This is to fix the following error:

[NameError] undefined local variable or method `x_active_tree'
app/helpers/application_helper/toolbar/custom_button_set_center.rb:24
...
[Original commit 8e505fcfa2bd8e269ccd7869cad657e0930cd9d3]