Item sorting for tagging: sorted items do not always have non-null names
This is to fix the following problem for example:
INFO -- : Started GET
"/cloud_volume/tagging_edit/1000000000009?db=CloudVolume&escape=false"
 INFO -- : Processing by CloudVolumeController#tagging_edit as HTML
 INFO -- :   Parameters: {"db"=>"CloudVolume", "escape"=>"false",
"id"=>"1000000000009"}
FATAL -- : Error caught: [NoMethodError] undefined method `downcase' for
nil:NilClass
app/controllers/application_controller/tags.rb:344:in `block in
tag_edit_build_screen'
app/controllers/application_controller/tags.rb:344:in `each'
app/controllers/application_controller/tags.rb:344:in `sort_by'
app/controllers/application_controller/tags.rb:344:in
`tag_edit_build_screen'
app/controllers/application_controller/tags.rb:167:in
`tagging_tags_set_form_vars'
app/controllers/application_controller/tags.rb:147:in
`tagging_edit_tags_reset'
app/controllers/application_controller/tags.rb:15:in `tagging_edit'
[Original commit f34a52325a9220745b4d8f539abab6e120e15256]